services:
  jenkins:
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_data:/var/jenkins_home

    image: jenkins/jenkins

  node-worker:
    image: jenkins/inbound-agent:latest
    container_name: worker
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4000:3000
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=my-node
      - JENKINS_SECRET=6422b88133eee8316c5b44c960e89ce0e1df51de24851248aef3cbdb0e237d33
    entrypoint: >
      bash -c "
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash - &&
      apt-get install -y nodejs &&
      sudo apt install docker.io -y &&
      apt-get clean &&
      npm i pnpm -g &&
      su jenkins -c '/usr/local/bin/jenkins-agent'"

volumes:
  jenkins_data:
